#!/usr/bin/env python

"""
csvcut is originally the work of eminent hackers Joe Germuska and Aaron Bycoffe.

This code is forked from:
https://gist.github.com/561347/9846ebf8d0a69b06681da9255ffe3d3f59ec2c97

Used and modified with permission.
"""

import sys

from csvkit import CSVKitWriter
from csvkit.cli import extract_csv_reader_kwargs, extract_csv_writer_kwargs, init_common_parser
from csvkit.cut import CSVCutReader

def main(args):
    """
    Command line-utility that filters and truncates CSV files. Like unix "cut" command, but for tabular data.
    """
    rows = CSVCutReader(args.file, args.columns, **extract_csv_reader_kwargs(args))

    if args.names_only:
        for i, c in enumerate(rows.next()):
            sys.stdout.write('%3i: %s\n' % (i + 1, c))

        sys.exit()

    output = CSVKitWriter(sys.stdout, **extract_csv_writer_kwargs(args))
    output.writerows(rows)

if __name__ == "__main__":
    """
    Process command line arguments.
    """
    parser = init_common_parser(description='Filter and truncate CSV files. Like unix "cut" command, but for tabular data.')
    parser.add_argument('-n', '--names', dest='names_only', action='store_true',
                        help='Display column names and indices from the input CSV and exit.')
    parser.add_argument('-c', '--columns', dest='columns',
                        help='A comma separated list of column indices or names to be extracted. Defaults to all columns.')

    main(parser.parse_args())
